#!/bin/bash

CUDA_VISIBLE_DEVICES=0 python ../../src/train_bash.py \
    --stage sft \
    --do_train \
    --model_name_or_path THUDM/chatglm3-6b-128k \
    --dataset  QA1,GJ1265_1shot,GJNegi1_1265shot,GJNegi2_1265shot,GJNegi3_1265shot,GJNegi4_1265shot,GJNegi5_1265shot,GJNegi6_1265shot \
    --dataset_dir ../../data \
    --template chatglm3 \
    --finetuning_type lora \
    --output_dir ../../../autodl-tmp/chatglmlora/train_GJNE1265shotnew\
    --overwrite_cache \
    --overwrite_output_dir \
    --cutoff_len 1024 \
    --preprocessing_num_workers 16 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --logging_steps 8 \
    --warmup_steps 20 \
    --save_steps 400 \
    --learning_rate 5e-5 \
    --num_train_epochs 2.0 \
    --max_samples 100000 \
    --fp16 True \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.1 \
    --lora_target query_key_value \
    --per_device_eval_batch_size 1 \
    --val_size 0.008 \
    --eval_steps 400 \
    --evaluation_strategy steps \
    --load_best_model_at_end \
    --plot_loss True
